# Site settings
title: Romantic Breaks
client:
  name: Lindor
  link: http://www.lindt.co.uk/shop/our-brands/lindor
description: >
  It’s that time of year again! Let us inspire you with our romantic collections, perfect for Valentine’s, and woo your loved one with luxurious moments. 
baseurl: "/romantic-breaks" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [js/scripts.min.js]
sass:
    sass_dir: css
    style: compressed